/**
 * Code Line entity - represents a single line of code with its segments and metadata
 */

import type { FoldInfo } from '../../CodeFold';
import type { CodeSegment } from '../../CodeSegment';

/**
 * Export slot information - represents an exported identifier on this line
 */
export interface ExportSlot {
  name: string; // Export identifier name
  nodeId?: string; // Original declaration node ID (if found by parser)
  offset?: number; // Offset in line (for sorting)
}

/**
 * A code line represents a single line of code with its segments and metadata
 * (domain model, UI-independent)
 */
export interface CodeLine {
  num: number;
  segments: CodeSegment[];
  hasInput: boolean;
  hasTopLevelReturn?: boolean;
  hasDeclarationKeyword?: boolean; // Line has declaration keyword (interface, type, class, enum, etc.)
  exportSlots?: ExportSlot[]; // export { foo, bar } statement slots
  foldInfo?: FoldInfo; // Fold metadata (generated by collectFoldMetadata)
}
